name: Serper Credit Monitoring

on:
  schedule:
    # Daily comprehensive report at 06:00 AM SAST (04:00 UTC)
    - cron: '0 4 * * *'
    # Hourly checks during business hours 08:00-20:00 SAST (06:00-18:00 UTC)
    - cron: '0 6,7,8,9,10,11,12,13,14,15,16,17,18 * * *'
  workflow_dispatch: # Allows manual triggering for testing
    inputs:
      check_type:
        description: 'Type of check to run'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - daily
          - hourly
          - force_alert

jobs:
  credit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Determine check type
        id: check_type
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "type=${{ github.event.inputs.check_type }}" >> $GITHUB_OUTPUT
          elif [ "$(date -u +%H)" = "04" ]; then
            echo "type=daily" >> $GITHUB_OUTPUT
          else
            echo "type=hourly" >> $GITHUB_OUTPUT
          fi

      - name: Run credit check
        env:
          SERPER_EMAIL: ${{ secrets.SERPER_EMAIL }}
          SERPER_PASSWORD: ${{ secrets.SERPER_PASSWORD }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          CHECK_TYPE: ${{ steps.check_type.outputs.type }}
          # Store previous credit count using GitHub's cache/state
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js

      - name: Archive logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ github.run_id }}
          path: |
            *.log
            screenshots/
          retention-days: 7